// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnrqkugkyamvkkakccoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpucnFrdWdreWFtdmtrYWtjY29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzU1NzMsImV4cCI6MjA2MjIxMTU3M30.joipDJcGdXGJMKm2p7259D4sDNu8mmxyR4oBt-qq4b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});